{
    'name' : "Bureau d'ordre",
    'version' : '1.0',
    'author' : 'GI 5 BI TEAM Workshop',
    'category' : 'ENSAH ERP',
    'sequence' : '1',
    'description' : "Desc",
    'website' : " web.site",
    'images' : [],
    'depends' : ['base'],
    'data' : ['br_departement_view.xml','br_organisation_view.xml','br_courrier_arrive_view.xml','br_courrier_arrive_wkf_view.xml'],
    'update_xml' : [],
    'js' : [],
    'qweb' : [],
    'css' : [],
    'demo' : [],
    'test' : [],
    'installable' : True,
    'auto_install' : False,
}